-- FEATABLE board all-in-one SQL (migrations 51-56)
-- Generated by scripts/build-board-sql-bundle.mjs. Do not edit this file by hand.
-- Requires the existing Featable schema through migration 50, including notifications.
-- Paste this entire file into the Supabase SQL Editor and run it once.
-- The bundle is idempotent and atomic: any failure rolls back the whole board update.

begin;

-- ============================================================================
-- migration-51-board.sql
-- ============================================================================

-- Migration 51: public board posts, comments, and post likes.
-- Safe to re-run: tables, policies, indexes, and trigger definitions are idempotent.


create table if not exists public.board_posts (
  id uuid primary key default uuid_generate_v4(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  display_name text not null default 'Featable 멤버',
  avatar_url text,
  author_visibility text not null default 'anonymous'
    check (author_visibility in ('anonymous', 'profile')),
  category text not null default 'free'
    check (category in ('free', 'question', 'feedback', 'team')),
  title text not null
    check (char_length(btrim(title)) between 2 and 120),
  body text not null
    check (char_length(btrim(body)) between 1 and 10000),
  status text not null default 'published'
    check (status in ('draft', 'published', 'hidden')),
  comment_count integer not null default 0
    check (comment_count >= 0),
  like_count integer not null default 0
    check (like_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep an already-created board_posts table aligned when this migration is rerun.
alter table public.board_posts alter column category set default 'free';
alter table public.board_posts
  add column if not exists author_visibility text;
update public.board_posts
set author_visibility = 'profile'
where author_visibility is null;
alter table public.board_posts
  alter column author_visibility set default 'anonymous';
alter table public.board_posts
  alter column author_visibility set not null;
alter table public.board_posts
  add column if not exists comment_count integer not null default 0;
alter table public.board_posts
  add column if not exists like_count integer not null default 0;
alter table public.board_posts drop constraint if exists board_posts_category_check;
update public.board_posts
set category = 'free'
where category not in ('free', 'question', 'feedback', 'team');
alter table public.board_posts add constraint board_posts_category_check
  check (category in ('free', 'question', 'feedback', 'team'));
alter table public.board_posts drop constraint if exists board_posts_author_visibility_check;
alter table public.board_posts add constraint board_posts_author_visibility_check
  check (author_visibility in ('anonymous', 'profile'));
alter table public.board_posts drop constraint if exists board_posts_comment_count_check;
alter table public.board_posts add constraint board_posts_comment_count_check
  check (comment_count >= 0);
alter table public.board_posts drop constraint if exists board_posts_like_count_check;
alter table public.board_posts add constraint board_posts_like_count_check
  check (like_count >= 0);

create table if not exists public.board_comments (
  id uuid primary key default uuid_generate_v4(),
  post_id uuid not null references public.board_posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  author_visibility text not null default 'anonymous'
    check (author_visibility in ('anonymous', 'profile')),
  display_name text not null default 'Featable 멤버',
  avatar_url text,
  body text not null
    check (char_length(btrim(body)) between 1 and 1000),
  status text not null default 'published'
    check (status in ('draft', 'published', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.board_post_likes (
  post_id uuid not null references public.board_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

alter table public.board_comments
  add column if not exists author_visibility text;
update public.board_comments
set author_visibility = 'profile'
where author_visibility is null
   or author_visibility not in ('anonymous', 'profile');
alter table public.board_comments
  alter column author_visibility set default 'anonymous',
  alter column author_visibility set not null;
alter table public.board_comments
  drop constraint if exists board_comments_author_visibility_check;
alter table public.board_comments
  add constraint board_comments_author_visibility_check
  check (author_visibility in ('anonymous', 'profile'));

-- Correct totals before installing the incremental counter trigger.
update public.board_posts p
set comment_count = (
  select count(*)::integer
  from public.board_comments c
  where c.post_id = p.id
    and c.status = 'published'
)
where p.comment_count is distinct from (
  select count(*)::integer
  from public.board_comments c
  where c.post_id = p.id
    and c.status = 'published'
);

update public.board_posts p
set like_count = (
  select count(*)::integer
  from public.board_post_likes l
  where l.post_id = p.id
)
where p.like_count is distinct from (
  select count(*)::integer
  from public.board_post_likes l
  where l.post_id = p.id
);

create index if not exists board_posts_public_feed_idx
  on public.board_posts(status, category, created_at desc);

create index if not exists board_posts_author_updated_idx
  on public.board_posts(author_id, updated_at desc);

create index if not exists board_posts_best_feed_idx
  on public.board_posts(like_count desc, created_at desc)
  where status = 'published' and like_count >= 10;

create index if not exists board_comments_post_created_idx
  on public.board_comments(post_id, created_at asc);

create index if not exists board_comments_author_updated_idx
  on public.board_comments(author_id, updated_at desc);

create index if not exists board_post_likes_user_created_idx
  on public.board_post_likes(user_id, created_at desc);

-- Author identity is copied from the profile at write time. A caller cannot
-- spoof the public name/avatar by sending display_name or avatar_url directly.
create or replace function public.sync_board_author_identity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_name text;
  profile_avatar_url text;
begin
  if new.author_id is null then
    new.author_id := auth.uid();
  end if;

  if new.author_id is null then
    raise exception 'board_author_required';
  end if;

  -- Authenticated users may only write as themselves. A service-role request
  -- has no auth.uid() and is allowed to write an explicitly supplied author.
  if auth.uid() is not null
    and new.author_id is distinct from auth.uid()
    and not public.is_admin() then
    raise exception 'board_author_mismatch';
  end if;

  if tg_table_name in ('board_posts', 'board_comments')
    and coalesce(to_jsonb(new) ->> 'author_visibility', 'anonymous') = 'anonymous' then
    new.display_name := '익명';
    new.avatar_url := null;
    return new;
  end if;

  select
    coalesce(
      nullif(trim(p.full_name), ''),
      nullif(trim(f.name), ''),
      'Featable 멤버'
    ),
    f.avatar_url
  into profile_name, profile_avatar_url
  from public.profiles p
  left join public.founders f on f.user_id = p.id
  where p.id = new.author_id;

  if not found then
    raise exception 'board_author_profile_not_found';
  end if;

  new.display_name := left(profile_name, 120);
  new.avatar_url := profile_avatar_url;
  return new;
end;
$$;

create or replace function public.set_board_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.sync_board_post_comment_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if new.status = 'published' then
      update public.board_posts
      set comment_count = comment_count + 1
      where id = new.post_id;
    end if;
  elsif tg_op = 'DELETE' then
    if old.status = 'published' then
      update public.board_posts
      set comment_count = greatest(comment_count - 1, 0)
      where id = old.post_id;
    end if;
  elsif old.post_id is distinct from new.post_id
    or old.status is distinct from new.status then
    if old.status = 'published' then
      update public.board_posts
      set comment_count = greatest(comment_count - 1, 0)
      where id = old.post_id;
    end if;

    if new.status = 'published' then
      update public.board_posts
      set comment_count = comment_count + 1
      where id = new.post_id;
    end if;
  end if;

  return null;
end;
$$;

create or replace function public.sync_board_post_like_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.board_posts
    set like_count = like_count + 1
    where id = new.post_id;
  elsif tg_op = 'DELETE' then
    update public.board_posts
    set like_count = greatest(like_count - 1, 0)
    where id = old.post_id;
  end if;

  return null;
end;
$$;

drop trigger if exists board_posts_sync_author_identity on public.board_posts;
create trigger board_posts_sync_author_identity
  before insert or update of author_id, author_visibility, display_name, avatar_url
  on public.board_posts
  for each row execute function public.sync_board_author_identity();

drop trigger if exists board_comments_sync_author_identity on public.board_comments;
create trigger board_comments_sync_author_identity
  before insert or update of author_id, author_visibility, display_name, avatar_url
  on public.board_comments
  for each row execute function public.sync_board_author_identity();

drop trigger if exists board_posts_set_updated_at on public.board_posts;
create trigger board_posts_set_updated_at
  before update on public.board_posts
  for each row execute function public.set_board_updated_at();

drop trigger if exists board_comments_set_updated_at on public.board_comments;
create trigger board_comments_set_updated_at
  before update on public.board_comments
  for each row execute function public.set_board_updated_at();

drop trigger if exists board_comments_sync_post_count on public.board_comments;
create trigger board_comments_sync_post_count
  after insert or delete or update of post_id, status on public.board_comments
  for each row execute function public.sync_board_post_comment_count();

drop trigger if exists board_post_likes_sync_post_count on public.board_post_likes;
create trigger board_post_likes_sync_post_count
  after insert or delete on public.board_post_likes
  for each row execute function public.sync_board_post_like_count();

alter table public.board_posts enable row level security;
alter table public.board_comments enable row level security;
alter table public.board_post_likes enable row level security;

drop policy if exists "board_posts_select_public" on public.board_posts;
create policy "board_posts_select_public" on public.board_posts
  for select to anon, authenticated
  using (status = 'published' or author_id = auth.uid() or public.is_admin());

drop policy if exists "board_posts_insert_own" on public.board_posts;
create policy "board_posts_insert_own" on public.board_posts
  for insert to authenticated
  with check (author_id = auth.uid() or public.is_admin());

drop policy if exists "board_posts_update_own" on public.board_posts;
create policy "board_posts_update_own" on public.board_posts
  for update to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

drop policy if exists "board_posts_delete_own" on public.board_posts;
create policy "board_posts_delete_own" on public.board_posts
  for delete to authenticated
  using (author_id = auth.uid());

drop policy if exists "board_comments_select_public" on public.board_comments;
create policy "board_comments_select_public" on public.board_comments
  for select to anon, authenticated
  using (
    (
      status = 'published'
      and exists (
        select 1
        from public.board_posts p
        where p.id = post_id
          and p.status = 'published'
      )
    )
    or author_id = auth.uid()
    or public.is_admin()
  );

drop policy if exists "board_comments_insert_own" on public.board_comments;
create policy "board_comments_insert_own" on public.board_comments
  for insert to authenticated
  with check (
    (author_id = auth.uid() or public.is_admin())
    and exists (
      select 1
      from public.board_posts p
      where p.id = post_id
        and (p.status = 'published' or p.author_id = auth.uid() or public.is_admin())
    )
  );

drop policy if exists "board_comments_update_own" on public.board_comments;
create policy "board_comments_update_own" on public.board_comments
  for update to authenticated
  using (author_id = auth.uid() or public.is_admin())
  with check (
    (author_id = auth.uid() or public.is_admin())
    and exists (
      select 1
      from public.board_posts p
      where p.id = post_id
        and (p.status = 'published' or p.author_id = auth.uid() or public.is_admin())
    )
  );

drop policy if exists "board_comments_delete_own" on public.board_comments;
create policy "board_comments_delete_own" on public.board_comments
  for delete to authenticated
  using (author_id = auth.uid() or public.is_admin());

drop policy if exists "board_post_likes_select_own" on public.board_post_likes;
create policy "board_post_likes_select_own" on public.board_post_likes
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "board_post_likes_insert_own" on public.board_post_likes;
create policy "board_post_likes_insert_own" on public.board_post_likes
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.board_posts p
      where p.id = post_id
        and p.status = 'published'
    )
  );

drop policy if exists "board_post_likes_delete_own" on public.board_post_likes;
create policy "board_post_likes_delete_own" on public.board_post_likes
  for delete to authenticated
  using (user_id = auth.uid());

-- Counter columns are trigger-owned. Authenticated clients may only write
-- content columns, so like/comment totals cannot be forged in direct requests.
revoke select, insert, update on public.board_posts from anon, authenticated;
grant select (
  id,
  display_name,
  avatar_url,
  author_visibility,
  category,
  title,
  body,
  status,
  comment_count,
  like_count,
  created_at,
  updated_at
)
  on public.board_posts to anon, authenticated;
grant insert (author_id, author_visibility, category, title, body, status)
  on public.board_posts to authenticated;
grant update (author_visibility, category, title, body)
  on public.board_posts to authenticated;

-- Comment editing/deletion is not exposed yet. Keep direct Data API access at
-- least privilege; future edit/delete flows should use a server action/RPC
-- that locks the parent post before mutating the comment.
revoke all on public.board_comments from anon, authenticated;
grant select (
  id,
  post_id,
  author_visibility,
  display_name,
  avatar_url,
  body,
  status,
  created_at,
  updated_at
)
  on public.board_comments to anon, authenticated;
grant insert (post_id, author_id, author_visibility, body)
  on public.board_comments to authenticated;

grant select, insert, delete on public.board_post_likes to authenticated;

-- ============================================================================
-- migration-52-board-views.sql
-- ============================================================================

-- Migration 52: deduplicated board post view counts.
-- A random browser-session key is stored only in an HttpOnly cookie and this
-- private table. No IP address or authenticated user id is collected.


alter table public.board_posts
  add column if not exists view_count integer not null default 0;

update public.board_posts
set view_count = 0
where view_count is null;

alter table public.board_posts
  alter column view_count set default 0,
  alter column view_count set not null;

alter table public.board_posts
  drop constraint if exists board_posts_view_count_check;
alter table public.board_posts
  add constraint board_posts_view_count_check check (view_count >= 0);

create table if not exists public.board_post_views (
  post_id uuid not null references public.board_posts(id) on delete cascade,
  viewer_key uuid not null,
  created_at timestamptz not null default now(),
  primary key (post_id, viewer_key)
);

alter table public.board_post_views enable row level security;
revoke all on public.board_post_views from public, anon, authenticated;

-- Count a published post at most once for a browser-session key. The post row
-- lock makes the view record and counter update atomic with status changes.
create or replace function public.record_board_post_view(
  p_post_id uuid,
  p_viewer_key uuid
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_count integer;
begin
  select view_count
  into current_count
  from public.board_posts
  where id = p_post_id
    and status = 'published'
  for update;

  if not found then
    return null;
  end if;

  insert into public.board_post_views (post_id, viewer_key)
  values (p_post_id, p_viewer_key)
  on conflict do nothing;

  if found then
    update public.board_posts
    set view_count = view_count + 1
    where id = p_post_id
    returning view_count into current_count;
  end if;

  return current_count;
end;
$$;

revoke all on function public.record_board_post_view(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.record_board_post_view(uuid, uuid)
  to service_role;

-- Counter-only updates must not make a post look content-edited. This also
-- keeps like/comment trigger updates from changing updated_at.
drop trigger if exists board_posts_set_updated_at on public.board_posts;
create trigger board_posts_set_updated_at
  before update of author_id, author_visibility, category, title, body, status
  on public.board_posts
  for each row execute function public.set_board_updated_at();

create index if not exists board_posts_public_views_idx
  on public.board_posts(view_count desc, created_at desc)
  where status = 'published';

grant select (view_count) on public.board_posts to anon, authenticated;

-- ============================================================================
-- migration-53-board-reports.sql
-- ============================================================================

-- Migration 53: board post/comment reports and removal of the legacy maker category.
-- Safe to re-run after migration-51-board.sql.


-- The legacy maker board is now part of the free board. Normalize rows before
-- replacing the category constraint so this remains safe for existing data.
update public.board_posts
set category = 'free'
where category = 'maker';

alter table public.board_posts
  alter column category set default 'free';

alter table public.board_posts
  drop constraint if exists board_posts_category_check;

alter table public.board_posts
  add constraint board_posts_category_check
  check (category in ('free', 'question', 'feedback', 'team'));

create table if not exists public.board_reports (
  id uuid primary key default uuid_generate_v4(),
  post_id uuid not null references public.board_posts(id) on delete cascade,
  comment_id uuid references public.board_comments(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reviewer_id uuid references public.profiles(id) on delete set null,
  reason text not null
    check (reason in ('spam', 'abuse', 'privacy', 'scam', 'copyright', 'other')),
  details text
    check (details is null or char_length(details) <= 500),
  status text not null default 'pending'
    check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep re-runs compatible with a table created by an earlier partial deploy.
alter table public.board_reports
  add column if not exists post_id uuid,
  add column if not exists comment_id uuid,
  add column if not exists reporter_id uuid,
  add column if not exists reviewer_id uuid,
  add column if not exists reason text,
  add column if not exists details text,
  add column if not exists status text,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

alter table public.board_reports
  alter column post_id set not null,
  alter column reporter_id set not null,
  alter column reason set not null,
  alter column status set default 'pending',
  alter column status set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'board_reports_post_id_fkey'
      and conrelid = 'public.board_reports'::regclass
  ) then
    alter table public.board_reports
      add constraint board_reports_post_id_fkey
      foreign key (post_id) references public.board_posts(id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'board_reports_comment_id_fkey'
      and conrelid = 'public.board_reports'::regclass
  ) then
    alter table public.board_reports
      add constraint board_reports_comment_id_fkey
      foreign key (comment_id) references public.board_comments(id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'board_reports_reporter_id_fkey'
      and conrelid = 'public.board_reports'::regclass
  ) then
    alter table public.board_reports
      add constraint board_reports_reporter_id_fkey
      foreign key (reporter_id) references public.profiles(id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'board_reports_reviewer_id_fkey'
      and conrelid = 'public.board_reports'::regclass
  ) then
    alter table public.board_reports
      add constraint board_reports_reviewer_id_fkey
      foreign key (reviewer_id) references public.profiles(id) on delete set null;
  end if;
end;
$$;

alter table public.board_reports
  drop constraint if exists board_reports_reason_check;
alter table public.board_reports
  add constraint board_reports_reason_check
  check (reason in ('spam', 'abuse', 'privacy', 'scam', 'copyright', 'other'));

alter table public.board_reports
  drop constraint if exists board_reports_details_length_check;
alter table public.board_reports
  add constraint board_reports_details_length_check
  check (details is null or char_length(details) <= 500);

alter table public.board_reports
  drop constraint if exists board_reports_status_check;
alter table public.board_reports
  add constraint board_reports_status_check
  check (status in ('pending', 'resolved', 'dismissed'));

-- A comment report must carry the parent post id and both ids must refer to
-- the same post. A cross-post pair must never be accepted by the API/RLS.
create or replace function public.validate_board_report_target()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  comment_post_id uuid;
  post_status text;
  comment_status text;
begin
  -- Serialize report creation with moderation of the same target. This closes
  -- the race where a pending report could be inserted just after a hide.
  select p.status
    into post_status
  from public.board_posts p
  where p.id = new.post_id
  for update;

  if not found or post_status <> 'published' then
    raise exception 'board_report_post_unavailable';
  end if;

  if new.comment_id is null then
    return new;
  end if;

  select c.post_id, c.status
    into comment_post_id, comment_status
  from public.board_comments c
  where c.id = new.comment_id
  for update;

  if comment_post_id is null or comment_post_id is distinct from new.post_id then
    raise exception 'board_report_comment_post_mismatch';
  end if;

  if comment_status <> 'published' then
    raise exception 'board_report_comment_unavailable';
  end if;

  return new;
end;
$$;

drop trigger if exists board_reports_validate_target on public.board_reports;
create trigger board_reports_validate_target
  before insert or update of post_id, comment_id
  on public.board_reports
  for each row execute function public.validate_board_report_target();

create or replace function public.set_board_report_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists board_reports_set_updated_at on public.board_reports;
create trigger board_reports_set_updated_at
  before update on public.board_reports
  for each row execute function public.set_board_report_updated_at();

-- One server-only transaction owns the entire moderation decision. The
-- service-role caller still supplies the verified admin id, which is checked
-- again here before it can be written to the audit record.
create or replace function public.moderate_board_report(
  p_report_id uuid,
  p_decision text,
  p_reviewer_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_post_id uuid;
  target_comment_id uuid;
  locked_post_id uuid;
  locked_comment_id uuid;
  current_status text;
begin
  if p_decision is null or p_decision not in ('dismiss', 'hide', 'delete') then
    raise exception 'board_report_invalid_decision';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = p_reviewer_id
      and p.role = 'admin'
  ) then
    raise exception 'board_report_reviewer_not_admin';
  end if;

  select br.post_id, br.comment_id, br.status
    into target_post_id, target_comment_id, current_status
  from public.board_reports br
  where br.id = p_report_id;

  if not found then
    raise exception 'board_report_not_found';
  end if;

  if current_status <> 'pending' then
    raise exception 'board_report_already_moderated';
  end if;

  if p_decision = 'dismiss' then
    select br.status
      into current_status
    from public.board_reports br
    where br.id = p_report_id
    for update;

    if not found then
      raise exception 'board_report_not_found';
    end if;

    if current_status <> 'pending' then
      raise exception 'board_report_already_moderated';
    end if;

    update public.board_reports
    set status = 'dismissed', reviewer_id = p_reviewer_id
    where id = p_report_id;
  else
    -- Lock in the same post-then-comment order used by report insertion.
    perform 1
    from public.board_posts p
    where p.id = target_post_id
    for update;

    if not found then
      raise exception 'board_report_target_not_found';
    end if;

    if target_comment_id is not null then
      perform 1
      from public.board_comments c
      where c.id = target_comment_id
        and c.post_id = target_post_id
      for update;

      if not found then
        raise exception 'board_report_target_not_found';
      end if;
    end if;

    -- Take the report lock only after the target locks. Report insertion uses
    -- the same target-then-report order, avoiding a moderation/insert deadlock.
    select br.post_id, br.comment_id, br.status
      into locked_post_id, locked_comment_id, current_status
    from public.board_reports br
    where br.id = p_report_id
    for update;

    if not found then
      raise exception 'board_report_not_found';
    end if;

    if locked_post_id is distinct from target_post_id
      or locked_comment_id is distinct from target_comment_id then
      raise exception 'board_report_target_changed';
    end if;

    if current_status <> 'pending' then
      raise exception 'board_report_already_moderated';
    end if;

    if p_decision = 'delete' then
      if target_comment_id is null then
        delete from public.board_posts
        where id = target_post_id;
      else
        delete from public.board_comments
        where id = target_comment_id
          and post_id = target_post_id;
      end if;
    else
      if target_comment_id is null then
        update public.board_posts
        set status = 'hidden'
        where id = target_post_id;
      else
        update public.board_comments
        set status = 'hidden'
        where id = target_comment_id
          and post_id = target_post_id;
      end if;

      update public.board_reports br
      set status = 'resolved', reviewer_id = p_reviewer_id
      where br.status = 'pending'
        and br.post_id = target_post_id
        and br.comment_id is not distinct from target_comment_id;
    end if;
  end if;

  return jsonb_build_object(
    'post_id', target_post_id,
    'comment_id', target_comment_id,
    'decision', p_decision
  );
end;
$$;

create unique index if not exists board_reports_reporter_post_unique
  on public.board_reports(reporter_id, post_id)
  where comment_id is null;

create unique index if not exists board_reports_reporter_comment_unique
  on public.board_reports(reporter_id, comment_id)
  where comment_id is not null;

create index if not exists board_reports_status_created_idx
  on public.board_reports(status, created_at desc);

create index if not exists board_reports_post_created_idx
  on public.board_reports(post_id, created_at desc);

create index if not exists board_reports_comment_created_idx
  on public.board_reports(comment_id, created_at desc)
  where comment_id is not null;

alter table public.board_reports enable row level security;

drop policy if exists "board_reports_select_own_or_admin" on public.board_reports;
create policy "board_reports_select_own_or_admin"
  on public.board_reports
  for select to authenticated
  using (reporter_id = auth.uid() or public.is_admin());

drop policy if exists "board_reports_insert_published_other" on public.board_reports;
create policy "board_reports_insert_published_other"
  on public.board_reports
  for insert to authenticated
  with check (
    reporter_id = auth.uid()
    and (
      (
        comment_id is null
        and exists (
          select 1
          from public.board_posts p
          where p.id = post_id
            and p.status = 'published'
            and p.author_id is distinct from auth.uid()
        )
      )
      or (
        comment_id is not null
        and exists (
          select 1
          from public.board_comments c
          join public.board_posts p on p.id = c.post_id
          where c.id = comment_id
            and c.post_id = board_reports.post_id
            and c.status = 'published'
            and p.status = 'published'
            and c.author_id is distinct from auth.uid()
        )
      )
    )
  );

-- Reports are not directly editable or deletable. Admin moderation goes
-- through the server-only transactional function below.
drop policy if exists "board_reports_admin_update" on public.board_reports;

revoke all on public.board_reports from anon, authenticated;

grant select (
  id,
  post_id,
  comment_id,
  reporter_id,
  reviewer_id,
  reason,
  details,
  status,
  created_at,
  updated_at
)
  on public.board_reports to authenticated;

grant insert (
  post_id,
  comment_id,
  reporter_id,
  reason,
  details
)
  on public.board_reports to authenticated;

revoke all on function public.moderate_board_report(uuid, text, uuid)
  from public, anon, authenticated;
grant execute on function public.moderate_board_report(uuid, text, uuid)
  to service_role;

-- ============================================================================
-- migration-54-board-author-actions.sql
-- ============================================================================

-- Migration 54: safe ownership checks and author-controlled board mutations.
-- Apply after migration-53-board-reports.sql.


-- Authors may edit content and identity visibility, but moderation state is
-- server/admin-owned. Revoke this explicitly for databases that already ran
-- an earlier version of migration 51.
revoke update (status)
  on public.board_posts from authenticated;

grant delete
  on public.board_posts to authenticated;

-- The public board actions are author-only. Admin moderation uses the
-- separately authenticated service-role path and bypasses these policies.
drop policy if exists "board_posts_update_own" on public.board_posts;
create policy "board_posts_update_own"
  on public.board_posts
  for update to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

drop policy if exists "board_posts_delete_own" on public.board_posts;
create policy "board_posts_delete_own"
  on public.board_posts
  for delete to authenticated
  using (author_id = auth.uid());

-- Anonymous author ids stay private. The detail UI receives only booleans and
-- ids belonging to the current session, never another member's author_id.
create or replace function public.get_my_board_ownership(p_post_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'owns_post',
      auth.uid() is not null
      and exists (
        select 1
        from public.board_posts p
        where p.id = p_post_id
          and p.author_id = auth.uid()
      ),
    'comment_ids',
      case
        when auth.uid() is null then '[]'::jsonb
        else coalesce(
          (
            select jsonb_agg(c.id order by c.created_at)
            from public.board_comments c
            where c.post_id = p_post_id
              and c.author_id = auth.uid()
              and c.status = 'published'
          ),
          '[]'::jsonb
        )
      end
  );
$$;

-- Direct comment update/delete stays closed. Deletion goes through this
-- function so the parent post is locked before the comment, matching report
-- moderation and keeping the comment counter transactionally consistent.
revoke update, delete
  on public.board_comments from anon, authenticated;

grant insert (post_id, author_id, author_visibility, body)
  on public.board_comments to authenticated;

create or replace function public.delete_own_board_comment(
  p_post_id uuid,
  p_comment_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
  comment_author_id uuid;
begin
  if current_user_id is null then
    return false;
  end if;

  perform 1
  from public.board_posts p
  where p.id = p_post_id
  for update;

  if not found then
    return false;
  end if;

  select c.author_id
    into comment_author_id
  from public.board_comments c
  where c.id = p_comment_id
    and c.post_id = p_post_id
  for update;

  if not found or comment_author_id is distinct from current_user_id then
    return false;
  end if;

  delete from public.board_comments
  where id = p_comment_id
    and post_id = p_post_id;

  return found;
end;
$$;

revoke all on function public.get_my_board_ownership(uuid)
  from public, anon, authenticated;
grant execute on function public.get_my_board_ownership(uuid)
  to authenticated;

revoke all on function public.delete_own_board_comment(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.delete_own_board_comment(uuid, uuid)
  to authenticated;

-- ============================================================================
-- migration-55-board-community-complete.sql
-- ============================================================================

-- Migration 55: comment identity choices and board activity notifications.
-- Apply after migration-54-board-author-actions.sql.


-- Preserve existing comments as profile-visible while making new comments
-- anonymous by default.
alter table public.board_comments
  add column if not exists author_visibility text;

update public.board_comments
set author_visibility = 'profile'
where author_visibility is null
   or author_visibility not in ('anonymous', 'profile');

alter table public.board_comments
  alter column author_visibility set default 'anonymous',
  alter column author_visibility set not null;

alter table public.board_comments
  drop constraint if exists board_comments_author_visibility_check;
alter table public.board_comments
  add constraint board_comments_author_visibility_check
  check (author_visibility in ('anonymous', 'profile'));

-- The same trusted trigger now protects identity snapshots for posts and
-- comments. Client-supplied display names and avatars are always overwritten.
create or replace function public.sync_board_author_identity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  profile_name text;
  profile_avatar_url text;
begin
  if new.author_id is null then
    new.author_id := auth.uid();
  end if;

  if new.author_id is null then
    raise exception 'board_author_required';
  end if;

  if auth.uid() is not null
    and new.author_id is distinct from auth.uid()
    and not public.is_admin() then
    raise exception 'board_author_mismatch';
  end if;

  if tg_table_name in ('board_posts', 'board_comments')
    and coalesce(to_jsonb(new) ->> 'author_visibility', 'anonymous') = 'anonymous' then
    new.display_name := '익명';
    new.avatar_url := null;
    return new;
  end if;

  select
    coalesce(
      nullif(trim(p.full_name), ''),
      nullif(trim(f.name), ''),
      'Featable 멤버'
    ),
    f.avatar_url
  into profile_name, profile_avatar_url
  from public.profiles p
  left join public.founders f on f.user_id = p.id
  where p.id = new.author_id;

  if not found then
    raise exception 'board_author_profile_not_found';
  end if;

  new.display_name := left(profile_name, 120);
  new.avatar_url := profile_avatar_url;
  return new;
end;
$$;

drop trigger if exists board_comments_sync_author_identity on public.board_comments;
create trigger board_comments_sync_author_identity
  before insert or update of author_id, author_visibility, display_name, avatar_url
  on public.board_comments
  for each row execute function public.sync_board_author_identity();

-- Reset the public API surface so author_id remains private even for profile
-- comments. Only the selected identity snapshot is publicly readable.
revoke all on public.board_comments from anon, authenticated;
grant select (
  id,
  post_id,
  author_visibility,
  display_name,
  avatar_url,
  body,
  status,
  created_at,
  updated_at
)
  on public.board_comments to anon, authenticated;
grant insert (post_id, author_id, author_visibility, body)
  on public.board_comments to authenticated;

-- Reassert the post column allowlist as part of the final bundle. In
-- particular, anonymous post author_id must never be queryable via REST.
revoke select on public.board_posts from anon, authenticated;
grant select (
  id,
  display_name,
  avatar_url,
  author_visibility,
  category,
  title,
  body,
  status,
  view_count,
  comment_count,
  like_count,
  created_at,
  updated_at
)
  on public.board_posts to anon, authenticated;

-- Each comment and each user/post like pair produces at most one notification.
create unique index if not exists notifications_board_comment_unique
  on public.notifications ((data ->> 'comment_id'))
  where data ->> 'kind' = 'board_comment';

create unique index if not exists notifications_board_like_unique
  on public.notifications (user_id, actor_id, (data ->> 'post_id'))
  where data ->> 'kind' = 'board_like';

create or replace function public.notify_board_comment_activity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  recipient_id uuid;
  post_title text;
begin
  if new.status <> 'published' then
    return new;
  end if;

  select p.author_id, p.title
    into recipient_id, post_title
  from public.board_posts p
  where p.id = new.post_id
    and p.status = 'published';

  if not found or recipient_id is not distinct from new.author_id then
    return new;
  end if;

  begin
    insert into public.notifications (
      user_id,
      actor_id,
      type,
      title,
      message,
      href,
      data
    ) values (
      recipient_id,
      case
        when new.author_visibility = 'profile' then new.author_id
        else null
      end,
      'system',
      '게시글에 새 댓글이 달렸어요',
      left(post_title, 120),
      '/board/' || new.post_id::text || '#comment-' || new.id::text,
      jsonb_build_object(
        'kind', 'board_comment',
        'post_id', new.post_id,
        'comment_id', new.id
      )
    )
    on conflict do nothing;
  exception when others then
    raise warning 'board comment notification skipped: %', sqlerrm;
  end;

  return new;
end;
$$;

create or replace function public.notify_board_like_activity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  recipient_id uuid;
  post_title text;
begin
  select p.author_id, p.title
    into recipient_id, post_title
  from public.board_posts p
  where p.id = new.post_id
    and p.status = 'published';

  if not found or recipient_id is not distinct from new.user_id then
    return new;
  end if;

  begin
    insert into public.notifications (
      user_id,
      actor_id,
      type,
      title,
      message,
      href,
      data
    ) values (
      recipient_id,
      new.user_id,
      'system',
      '게시글에 좋아요가 추가됐어요',
      left(post_title, 120),
      '/board/' || new.post_id::text || '#board-post-reactions',
      jsonb_build_object(
        'kind', 'board_like',
        'post_id', new.post_id
      )
    )
    on conflict do nothing;
  exception when others then
    raise warning 'board like notification skipped: %', sqlerrm;
  end;

  return new;
end;
$$;

drop trigger if exists board_comments_notify_author on public.board_comments;
create trigger board_comments_notify_author
  after insert on public.board_comments
  for each row execute function public.notify_board_comment_activity();

drop trigger if exists board_post_likes_notify_author on public.board_post_likes;
create trigger board_post_likes_notify_author
  after insert on public.board_post_likes
  for each row execute function public.notify_board_like_activity();

revoke all on function public.notify_board_comment_activity()
  from public, anon, authenticated;
revoke all on function public.notify_board_like_activity()
  from public, anon, authenticated;

-- ============================================================================
-- migration-56-board-images.sql
-- ============================================================================

-- Migration 56: board image attachments.
--
-- The service upload route owns Storage writes. It uploads an object to the
-- public board-images bucket and inserts a pending board_post_images row with
-- the authenticated uploader_id by using the service role. The authenticated
-- RPCs below then attach those pending rows atomically to a post.
--
-- Safe to re-run: schema objects, policies, triggers, and function grants are
-- recreated idempotently. Storage objects are never deleted by SQL; deleting
-- an attachment queues its path for a service-role cleanup worker.


-- --------------------------------------------------------------------------
-- Public board image bucket. Direct anon/authenticated writes are blocked by
-- restrictive storage policies below. The service-role upload route bypasses
-- RLS and remains the only writer.
-- --------------------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'board-images',
  'board-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table storage.objects enable row level security;

drop policy if exists "board_images_public_read" on storage.objects;
create policy "board_images_public_read"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'board-images');

-- PostgreSQL RLS policies are permissive by default. These restrictive
-- policies make a future broad storage INSERT/UPDATE/DELETE policy unable to
-- open this bucket to the browser while preserving the existing images bucket
-- upload policy used elsewhere in Featable.
drop policy if exists "board_images_block_direct_insert" on storage.objects;
create policy "board_images_block_direct_insert"
  on storage.objects
  as restrictive
  for insert
  to anon, authenticated
  with check (bucket_id <> 'board-images');

drop policy if exists "board_images_block_direct_update" on storage.objects;
create policy "board_images_block_direct_update"
  on storage.objects
  as restrictive
  for update
  to anon, authenticated
  using (bucket_id <> 'board-images')
  with check (bucket_id <> 'board-images');

drop policy if exists "board_images_block_direct_delete" on storage.objects;
create policy "board_images_block_direct_delete"
  on storage.objects
  as restrictive
  for delete
  to anon, authenticated
  using (bucket_id <> 'board-images');

-- --------------------------------------------------------------------------
-- Attachment rows. A pending row has no post_id. The service upload route
-- creates it after Storage upload; an authenticated RPC attaches it to the
-- caller's post. The uploader UUID is intentionally absent from public grants.
-- --------------------------------------------------------------------------

create table if not exists public.board_post_images (
  id uuid primary key default uuid_generate_v4(),
  post_id uuid references public.board_posts(id) on delete cascade,
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  storage_path text not null unique,
  mime_type text not null
    check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  byte_size integer not null
    check (byte_size between 1 and 5242880),
  width integer
    check (width is null or width between 1 and 10000),
  height integer
    check (height is null or height between 1 and 10000),
  sort_order smallint not null default 0
    check (sort_order between 0 and 4),
  alt_text text not null default ''
    check (char_length(alt_text) <= 200),
  status text not null default 'pending'
    check (status in ('pending', 'attached')),
  created_at timestamptz not null default now(),
  attached_at timestamptz,
  check (
    (status = 'pending' and post_id is null and attached_at is null)
    or
    (status = 'attached' and post_id is not null and attached_at is not null)
  ),
  check (
    storage_path ~
    '^board/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp)$'
  )
);

create index if not exists board_post_images_post_order_idx
  on public.board_post_images(post_id, sort_order, created_at)
  where status = 'attached';

create index if not exists board_post_images_uploader_pending_idx
  on public.board_post_images(uploader_id, created_at desc)
  where status = 'pending';

-- Keep the table private by default. Public pages receive only the selected
-- image metadata; uploader_id is usable by RLS but not queryable through REST.
alter table public.board_post_images enable row level security;
revoke all on public.board_post_images from public, anon, authenticated;

drop policy if exists "board_post_images_select_visible" on public.board_post_images;
create policy "board_post_images_select_visible"
  on public.board_post_images
  for select
  to anon, authenticated
  using (
    (
      status = 'attached'
      and post_id is not null
      and exists (
        select 1
        from public.board_posts p
        where p.id = board_post_images.post_id
          and p.status = 'published'
      )
    )
    or (
      status = 'pending'
      and post_id is null
      and uploader_id = auth.uid()
    )
    or (
      status = 'attached'
      and exists (
        select 1
        from public.board_posts p
        where p.id = board_post_images.post_id
          and p.author_id = auth.uid()
      )
    )
    or public.is_admin()
  );

grant select (
  id,
  post_id,
  storage_path,
  mime_type,
  byte_size,
  width,
  height,
  sort_order,
  alt_text,
  status,
  created_at,
  attached_at
)
  on public.board_post_images
  to anon, authenticated;

-- No INSERT/UPDATE/DELETE grant or permissive policy is exposed to anon or
-- authenticated. Pending rows and Storage objects are service-route writes;
-- the RPCs are the only authenticated mutation surface.

-- The upload route uses this service-role-only function after the Storage
-- object is written. The per-user advisory lock makes the pending quota
-- atomic even when a client sends many uploads concurrently.
create or replace function public.register_board_image_upload(
  p_uploader_id uuid,
  p_storage_path text,
  p_mime_type text,
  p_byte_size integer
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_image_id uuid;
  pending_count integer;
begin
  if p_uploader_id is null then
    raise exception 'board_image_uploader_required';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_uploader_id::text, 20260825)
  );

  select count(*)::integer
    into pending_count
  from public.board_post_images i
  where i.uploader_id = p_uploader_id
    and i.status = 'pending';

  if pending_count >= 20 then
    raise exception 'board_image_pending_limit';
  end if;

  insert into public.board_post_images (
    post_id,
    uploader_id,
    storage_path,
    mime_type,
    byte_size,
    status
  ) values (
    null,
    p_uploader_id,
    p_storage_path,
    p_mime_type,
    p_byte_size,
    'pending'
  )
  returning id into new_image_id;

  return new_image_id;
end;
$$;

revoke all on function public.register_board_image_upload(uuid, text, text, integer)
  from public, anon, authenticated;
grant execute on function public.register_board_image_upload(uuid, text, text, integer)
  to service_role;

-- --------------------------------------------------------------------------
-- Storage cleanup queue. ON DELETE CASCADE removes attachment rows but cannot
-- remove a Storage object, so every row deletion records its path for a
-- service-role worker to remove and mark processed.
-- --------------------------------------------------------------------------

create table if not exists public.board_image_cleanup_queue (
  id uuid primary key default uuid_generate_v4(),
  storage_path text not null unique,
  queued_at timestamptz not null default now(),
  processed_at timestamptz,
  attempts integer not null default 0
    check (attempts >= 0),
  last_attempt_at timestamptz,
  last_error text
);

alter table public.board_image_cleanup_queue enable row level security;
revoke all on public.board_image_cleanup_queue from public, anon, authenticated;

create or replace function public.queue_board_image_cleanup()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.board_image_cleanup_queue (storage_path)
  values (old.storage_path)
  on conflict (storage_path) do nothing;
  return old;
end;
$$;

drop trigger if exists board_post_images_queue_cleanup on public.board_post_images;
create trigger board_post_images_queue_cleanup
  after delete on public.board_post_images
  for each row execute function public.queue_board_image_cleanup();

revoke all on function public.queue_board_image_cleanup() from public, anon, authenticated;

-- --------------------------------------------------------------------------
-- Enforce the five-image limit under a parent-row lock so concurrent uploads
-- cannot race past an application-only count check.
-- --------------------------------------------------------------------------

create or replace function public.enforce_board_post_image_limit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_count integer;
begin
  if new.status <> 'attached' or new.post_id is null then
    return new;
  end if;

  perform 1
  from public.board_posts p
  where p.id = new.post_id
  for update;

  if not found then
    raise exception 'board_post_not_found';
  end if;

  select count(*)::integer
    into current_count
  from public.board_post_images i
  where i.post_id = new.post_id
    and i.status = 'attached'
    and i.id is distinct from new.id;

  if current_count >= 5 then
    raise exception 'board_images_too_many';
  end if;

  return new;
end;
$$;

drop trigger if exists board_post_images_enforce_limit on public.board_post_images;
create trigger board_post_images_enforce_limit
  before insert or update of post_id, status on public.board_post_images
  for each row execute function public.enforce_board_post_image_limit();

revoke all on function public.enforce_board_post_image_limit() from public, anon, authenticated;

-- --------------------------------------------------------------------------
-- Create a published post and attach the caller's pending images atomically.
-- The service route must create pending rows first; this function never trusts
-- client-supplied uploader_id, Storage metadata, or display identity fields.
-- --------------------------------------------------------------------------

create or replace function public.create_board_post_with_images(
  p_category text,
  p_author_visibility text,
  p_title text,
  p_body text,
  p_image_ids uuid[]
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
  image_ids uuid[] := coalesce(p_image_ids, '{}'::uuid[]);
  image_count integer;
  new_post_id uuid;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if p_category is null or p_category not in ('free', 'question', 'feedback', 'team') then
    raise exception 'board_category_invalid';
  end if;

  if p_author_visibility is null or p_author_visibility not in ('anonymous', 'profile') then
    raise exception 'board_author_visibility_invalid';
  end if;

  if char_length(btrim(coalesce(p_title, ''))) not between 2 and 120 then
    raise exception 'board_title_invalid';
  end if;

  if char_length(btrim(coalesce(p_body, ''))) not between 1 and 10000 then
    raise exception 'board_body_invalid';
  end if;

  if exists (select 1 from unnest(image_ids) as item(image_id) where item.image_id is null) then
    raise exception 'board_images_invalid';
  end if;

  if cardinality(image_ids) > 5 then
    raise exception 'board_images_too_many';
  end if;

  if exists (
    select item.image_id
    from unnest(image_ids) as item(image_id)
    group by item.image_id
    having count(*) > 1
  ) then
    raise exception 'board_images_invalid';
  end if;

  -- Lock selected rows before validating and attaching them.
  perform 1
  from public.board_post_images i
  where i.id = any(image_ids)
  for update;

  select count(*)::integer
    into image_count
  from public.board_post_images i
  where i.id = any(image_ids)
    and i.status = 'pending'
    and i.post_id is null
    and i.uploader_id = current_user_id;

  if image_count <> cardinality(image_ids) then
    raise exception 'board_images_invalid';
  end if;

  insert into public.board_posts (
    author_id,
    author_visibility,
    category,
    title,
    body,
    status
  ) values (
    current_user_id,
    p_author_visibility,
    p_category,
    btrim(p_title),
    btrim(p_body),
    'published'
  )
  returning id into new_post_id;

  update public.board_post_images i
  set post_id = new_post_id,
      status = 'attached',
      attached_at = now(),
      sort_order = (selected.ord - 1)::smallint
  from (
    select item.image_id, item.ord
    from unnest(image_ids) with ordinality as item(image_id, ord)
  ) as selected
  where i.id = selected.image_id;

  return new_post_id;
end;
$$;

-- --------------------------------------------------------------------------
-- Update an owned post and replace its attached image set atomically.
-- removed_paths is returned so the service route can eagerly remove Storage
-- objects; the delete trigger also queues them for retry-safe cleanup.
-- --------------------------------------------------------------------------

create or replace function public.update_board_post_with_images(
  p_post_id uuid,
  p_category text,
  p_author_visibility text,
  p_title text,
  p_body text,
  p_image_ids uuid[]
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
  image_ids uuid[] := coalesce(p_image_ids, '{}'::uuid[]);
  image_count integer;
  locked_post_id uuid;
  removed_paths jsonb;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  select p.id
    into locked_post_id
  from public.board_posts p
  where p.id = p_post_id
    and p.author_id = current_user_id
  for update;

  if not found then
    raise exception 'board_post_not_owned';
  end if;

  if p_category is null or p_category not in ('free', 'question', 'feedback', 'team') then
    raise exception 'board_category_invalid';
  end if;

  if p_author_visibility is null or p_author_visibility not in ('anonymous', 'profile') then
    raise exception 'board_author_visibility_invalid';
  end if;

  if char_length(btrim(coalesce(p_title, ''))) not between 2 and 120 then
    raise exception 'board_title_invalid';
  end if;

  if char_length(btrim(coalesce(p_body, ''))) not between 1 and 10000 then
    raise exception 'board_body_invalid';
  end if;

  if exists (select 1 from unnest(image_ids) as item(image_id) where item.image_id is null) then
    raise exception 'board_images_invalid';
  end if;

  if cardinality(image_ids) > 5 then
    raise exception 'board_images_too_many';
  end if;

  if exists (
    select item.image_id
    from unnest(image_ids) as item(image_id)
    group by item.image_id
    having count(*) > 1
  ) then
    raise exception 'board_images_invalid';
  end if;

  -- Lock selected rows before checking ownership or calculating removals.
  perform 1
  from public.board_post_images i
  where i.id = any(image_ids)
  for update;

  select count(*)::integer
    into image_count
  from public.board_post_images i
  where i.id = any(image_ids)
    and i.uploader_id = current_user_id
    and (
      (i.status = 'pending' and i.post_id is null)
      or (i.status = 'attached' and i.post_id = p_post_id)
    );

  if image_count <> cardinality(image_ids) then
    raise exception 'board_images_invalid';
  end if;

  select coalesce(
    jsonb_agg(i.storage_path order by i.sort_order, i.created_at),
    '[]'::jsonb
  )
    into removed_paths
  from public.board_post_images i
  where i.post_id = p_post_id
    and i.status = 'attached'
    and not (i.id = any(image_ids));

  delete from public.board_post_images i
  where i.post_id = p_post_id
    and i.status = 'attached'
    and not (i.id = any(image_ids));

  update public.board_posts
  set author_visibility = p_author_visibility,
      category = p_category,
      title = btrim(p_title),
      body = btrim(p_body)
  where id = p_post_id;

  update public.board_post_images i
  set post_id = p_post_id,
      status = 'attached',
      attached_at = coalesce(i.attached_at, now()),
      sort_order = (selected.ord - 1)::smallint
  from (
    select item.image_id, item.ord
    from unnest(image_ids) with ordinality as item(image_id, ord)
  ) as selected
  where i.id = selected.image_id;

  return jsonb_build_object(
    'post_id', p_post_id,
    'removed_paths', removed_paths
  );
end;
$$;

revoke all on function public.create_board_post_with_images(text, text, text, text, uuid[])
  from public, anon, authenticated;
grant execute on function public.create_board_post_with_images(text, text, text, text, uuid[])
  to authenticated;

revoke all on function public.update_board_post_with_images(uuid, text, text, text, text, uuid[])
  from public, anon, authenticated;
grant execute on function public.update_board_post_with_images(uuid, text, text, text, text, uuid[])
  to authenticated;

commit;
