// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import handler from "./.open-next/worker.js";

type FeatableWorkerEnv = { SYNC_CRON_SECRET?: string };
type WorkerContext = { waitUntil(promise: Promise<unknown>): void };
type ScheduledEvent = { cron: string };

const worker = {
  fetch: handler.fetch,
  async scheduled(event: ScheduledEvent, env: FeatableWorkerEnv, ctx: WorkerContext) {
    if (!env.SYNC_CRON_SECRET) throw new Error("SYNC_CRON_SECRET is missing.");
    const paths = event.cron === "0 */6 * * *"
      ? ["/api/cron/bizinfo", "/api/cron/interview-emails"]
      : ["/api/cron/interview-emails"];
    for (const path of paths) {
      const request = new Request(`https://featable.kr${path}`, {
        method: "POST",
        headers: { authorization: `Bearer ${env.SYNC_CRON_SECRET}`, "x-featable-cron": event.cron },
      });
      const response = await handler.fetch(request, env, ctx);
      if (!response.ok) throw new Error(`${path} failed (${response.status}): ${await response.text()}`);
    }
  },
};

export default worker;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
