// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import handler from "./.open-next/worker.js";

type FeatableWorkerEnv = { SYNC_CRON_SECRET?: string };
type WorkerContext = { waitUntil(promise: Promise<unknown>): void };
type ScheduledEvent = { cron: string };

const worker = {
  async fetch(request: Request, env: FeatableWorkerEnv, ctx: WorkerContext) {
    const url = new URL(request.url);
    if (url.protocol === "http:" || request.headers.get("x-forwarded-proto") === "http") {
      url.protocol = "https:";
      return Response.redirect(url, 308);
    }
    return handler.fetch(request, env, ctx);
  },
  async scheduled(event: ScheduledEvent, env: FeatableWorkerEnv, ctx: WorkerContext) {
    if (!env.SYNC_CRON_SECRET) throw new Error("SYNC_CRON_SECRET is missing.");
    let paths: string[];
    if (event.cron === "0 */6 * * *") {
      paths = ["/api/cron/bizinfo", "/api/cron/interview-emails", "/api/cron/board-images"];
    } else if (event.cron === "55 14 * * *") {
      paths = ["/api/cron/board-balance?target=tomorrow"];
    } else if (event.cron === "0 15 * * *") {
      paths = ["/api/cron/board-balance"];
    } else {
      paths = ["/api/cron/board-balance", "/api/cron/interview-emails"];
    }
    for (const path of paths) {
      const request = new Request(`https://featable.kr${path}`, {
        method: "POST",
        headers: { authorization: `Bearer ${env.SYNC_CRON_SECRET}`, "x-featable-cron": event.cron },
      });
      const response = await handler.fetch(request, env, ctx);
      if (!response.ok) throw new Error(`${path} failed (${response.status}): ${await response.text()}`);
    }
  },
};

export default worker;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
